version: '3.3'

services:
  engagement-bot:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: engagement-bot
    restart: always
    depends_on:
      - db
      - redis
#    env_file:
#      - .env
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: bot-postgres-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bot_db
      SQLALCHEMY_DATABASE_URI: postgresql+asyncpg://postgres:root1234@db:5432/bot_db

    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:16.4-bookworm
    container_name: bot-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_SERVER: bot-postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: chatbot-redis-cache
    ports:
      - "6379:6379"


volumes:
  postgres_data:


networks:
  bot-network:
    external: true